version: '3.8'
services:
  kafka1:
    image: bitnami/kafka:3.6
    hostname: kafka1
    container_name: kafka1
    ports:
      - target: 9192
        published: 9190
        protocol: tcp
      - target: 9193
        published: 9193
        protocol: tcp
    environment:
    - KAFKA_CFG_NODE_ID=1
    - KAFKA_CFG_BROKER_RACK=RACK1
    - KAFKA_CFG_PROCESS_ROLES=broker, controller
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_CFG_LISTENERS=CONTROLLER://:9193, DOCKER_EXTERNAL://kafka1:9190, DOCKER_INTERNAL://kafka1:9192
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT,DOCKER_INTERNAL:PLAINTEXT
    - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=DOCKER_INTERNAL
    - KAFKA_CFG_ADVERTISED_LISTENERS=DOCKER_EXTERNAL://kafka1:9190, DOCKER_INTERNAL://kafka1:9192
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9193,2@kafka2:9193,3@kafka3:9193
    - KAFKA_KRAFT_CLUSTER_ID=NTg20wZhNzY3NDhjMTFlZG
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_OPTS=-Dlog4j.rootLogger=DEBUG
    volumes:
      - kafka1_data:/bitnami/kafka
    networks:
      - kafkanet

  kafka2:
    image: bitnami/kafka:3.6
    hostname: kafka2
    container_name: kafka2
    ports:
      - target: 9192
        published: 9191
        protocol: tcp
      - target: 9193
        published: 9194
        protocol: tcp
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_BROKER_RACK=RACK2
      - KAFKA_CFG_PROCESS_ROLES=broker, controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9193, DOCKER_EXTERNAL://kafka2:9191, DOCKER_INTERNAL://kafka2:9192
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT,DOCKER_INTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=DOCKER_INTERNAL
      - KAFKA_CFG_ADVERTISED_LISTENERS=DOCKER_EXTERNAL://kafka2:9191, DOCKER_INTERNAL://kafka2:9192
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9193, 2@kafka2:9193, 3@kafka3:9193
      - KAFKA_KRAFT_CLUSTER_ID=NTg20wZhNzY3NDhjMTFlZG
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_OPTS=-Dlog4j.rootLogger=DEBUG
    volumes:
      - kafka2_data:/bitnami/kafka
    networks:
      - kafkanet


  kafka3:
    image: bitnami/kafka:3.6
    hostname: kafka3
    container_name: kafka3
    ports:
      - target: 9192
        published: 9192
        protocol: tcp
      - target: 9193
        published: 9195
        protocol: tcp
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_BROKER_RACK=RACK3
      - KAFKA_CFG_PROCESS_ROLES=broker, controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9193, DOCKER_EXTERNAL://kafka3:9195, DOCKER_INTERNAL://kafka3:9192
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT,DOCKER_INTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=DOCKER_INTERNAL
      - KAFKA_CFG_ADVERTISED_LISTENERS=DOCKER_EXTERNAL://kafka3:9192, DOCKER_INTERNAL://kafka3:9192
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9193, 2@kafka2:9193, 3@kafka3:9193
      - KAFKA_KRAFT_CLUSTER_ID=NTg20wZhNzY3NDhjMTFlZG
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_OPTS=-Dlog4j.rootLogger=DEBUG
    volumes:
      - kafka3_data:/bitnami/kafka
    networks:
      - kafkanet
volumes:
    kafka1_data:
      driver: local
    kafka2_data:
      driver: local
    kafka3_data:
      driver: local
networks:
  kafkanet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.26.0.0/16
